name: Static analysis
on: [push, pull_request]

jobs:
  errcheck:
    name: Errcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@v1.0.0
      with:
        run: errcheck
        token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@v1.0.0
      with:
        run: lint
        token: ${{ secrets.GITHUB_TOKEN }}

  # Disabling this while we have plenty of unused
  # types and fields.
  #
  # staticcheck:
    # name: StaticCheck
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@master
    # - name: check
      # uses: grandcolline/golang-github-actions@v1.0.0
      # with:
        # run: staticcheck
        # token: ${{ secrets.GITHUB_TOKEN }}

  sec:
    name: Sec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@v1.0.0
      with:
        run: sec
        token: ${{ secrets.GITHUB_TOKEN }}
